---
title: "Import"
---

Standard packages are:

```{r,message=FALSE, warning=FALSE, echo = TRUE}
library(readr)
library(tibble)
library(jsonlite)
library(tidyverse)
library(dplyr)
library(shiny)
library(refund)
library(face)
library(fields)
library(trelliscope)
library(ggplot2)
```

## Information Required

The analysis requires the following information for each athlete and event observation.\

-Athlete identifier, which includes name and athlete link\
-Performance, which is time for races and distance\
-Event type, which comes from the event field\
-Date of performance, which comes from the "date" field\
-Birthdate, which comes from the "Birth.Date" field\
-Athlete age at the time of performance, derived from "Birthdate" and "Date of performance"

## Data Sources

This project requires three datasets in total. Two datasets will be obtained from WorldAthelete.org and imported with `read_csv()`. These two datasets contains only the best performance per year for each athlete in each event. That means if an athlete participates in the same event multiple times in a year, only their top result is included. If the same athlete competes in multiple events in the same year, they will have one record for each event. And another `iaaf-2005.json` dataset is obtained from xxxx's github and imported with `read_json()` .

-   The file `career_progression.csv` contains performance data, year, date, event, and athlete-link(identifiers).
-   The file `olympics_data.csv` provides athlete level metadata including name, birthdate, gender, event, game, game-link, athlete-link, nationality, and Olympic appearances(for example: performance mark and their rank)
-   The file `iaaf-2005.json` provides iaaf-points, mark and gender per event

## Collection Method

The two athlete related datasets have already been downloaded and imported manually using the standard read-csv() procedure. From "Birthdate" and "Performance date" we will compute the athlete age in years at the time of performance. Age is essential because aging curves are indexed by age rather than by calendar date. Additionally, the iaaf-2005.json dataset is also downloaded and imported manually. We need to convert individual athlete's performance marks to a standard IAAF-points, so that we can compare their aging curves based on the IAAF-points across different events.

## Frequency of Collection

A single collection is sufficient for this study because the focus is historical performance progression. The analysis is not designed for live or streaming updates. Any future extensions that add seasons or events can append to these files and rerun the same pipeline.

## Assumptions and Data Preparation Notes

\- Athlete age is measured in years using the difference between performance date and birthdate.\
- Performance is standardized for cross event comparison using IAAF points.\
- Each row in the linked dataset (linked `career_progression.csv` and `olympics_data.csv` ) represents one athlete performance on one date for one event. (details in tidy chapter)\
- Athlete identifier fields must be consistent across files to enable a reliable merge.\
- Basic integrity checks such as duplicate detection and valid date parsing will be performed in the tidy chapter.
