project:
  type: website
  output-dir: docs

book:
  title: "Stat 468 final project"
  author: "Yushi Liu"
  date: "2025-08-07"
  chapters:
    - index.qmd
    - 01-question.qmd
    - 02-import.qmd
    - 03-tidy.qmd
    - 04-transform.qmd
    - 05-visualize.qmd
    - 06-model.qmd
    - 07-communicate.qmd
    - appendix.qmd


format:
  html:
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    theme: cosmo

editor: visual
execute: 
  eval: false
  warning: false
  message: false
  echo: true

bibliography: references.bib